cfg:
  sample_rate: 16000
  labels:
  - Q
  - a
  - 'a:'
  - aˤ
  - 'aˤ:'
  - b
  - bb
  - d
  - dd
  - dˤ
  - dˤdˤ
  - f
  - ff
  - h
  - hh
  - i
  - 'i:'
  - j
  - jj
  - j̃
  - k
  - kk
  - l
  - ll
  - lˤlˤ
  - m
  - m̃
  - 'n'
  - q
  - qq
  - r
  - rr
  - rˤ
  - rˤrˤ
  - s
  - ss
  - sˤ
  - sˤsˤ
  - t
  - tt
  - tˤ
  - tˤtˤ
  - u
  - 'u:'
  - w
  - ww
  - w̃
  - x
  - xx
  - z
  - zz
  - ð
  - ðð
  - ðˤ
  - ðˤðˤ
  - ñ
  - ħ
  - ŋ
  - ɣ
  - ʃ
  - ʃʃ
  - ʒ
  - ʒʒ
  - ʔ
  - ʕ
  - ʕʕ
  - θ
  - θθ
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: 16000
    normalize: per_feature
    window_size: 0.025
    window_stride: 0.01
    window: hann
    features: 80
    n_fft: 512
    frame_splicing: 1
    dither: 1.0e-05
    pad_to: 0
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2
    freq_width: 27
    time_masks: 5
    time_width: 0.05
  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: 80
    feat_out: -1
    n_layers: 17
    d_model: 512
    subsampling: dw_striding
    subsampling_factor: 8
    subsampling_conv_channels: 256
    ff_expansion_factor: 4
    self_attention_model: rel_pos_local_attn
    n_heads: 8
    att_context_size:
    - 128
    - 128
    xscaling: true
    untie_biases: true
    pos_emb_max_len: 5000
    conv_kernel_size: 9
    dropout: 0.1
    dropout_emb: 0.0
    dropout_att: 0.1
  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: 512
    num_classes: 68
    vocabulary:
    - Q
    - a
    - 'a:'
    - aˤ
    - 'aˤ:'
    - b
    - bb
    - d
    - dd
    - dˤ
    - dˤdˤ
    - f
    - ff
    - h
    - hh
    - i
    - 'i:'
    - j
    - jj
    - j̃
    - k
    - kk
    - l
    - ll
    - lˤlˤ
    - m
    - m̃
    - 'n'
    - q
    - qq
    - r
    - rr
    - rˤ
    - rˤrˤ
    - s
    - ss
    - sˤ
    - sˤsˤ
    - t
    - tt
    - tˤ
    - tˤtˤ
    - u
    - 'u:'
    - w
    - ww
    - w̃
    - x
    - xx
    - z
    - zz
    - ð
    - ðð
    - ðˤ
    - ðˤðˤ
    - ñ
    - ħ
    - ŋ
    - ɣ
    - ʃ
    - ʃʃ
    - ʒ
    - ʒʒ
    - ʔ
    - ʕ
    - ʕʕ
    - θ
    - θθ
  loss:
    _target_: nemo.collections.asr.losses.CTCLoss
    num_classes: 68
    zero_infinity: true
    reduction: mean_batch
  train_ds:
    manifest_filepath: data/manifest_train.json
    sample_rate: 16000
    batch_size: 16
    shuffle: true
    num_workers: 0
    pin_memory: true
    trim_silence: false
    max_duration: 30.0
    min_duration: 0.5
  validation_ds:
    manifest_filepath: data/manifest_dev.json
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 0
    pin_memory: true
    trim_silence: false
  optim:
    name: adamw
    lr: 0.0005
    betas:
    - 0.9
    - 0.98
    weight_decay: 0.001
    sched:
      name: CosineAnnealing
      warmup_steps: 500
      min_lr: 1.0e-06
  target: nemo.collections.asr.models.ctc_models.EncDecCTCModel
  nemo_version: 2.7.3
